'use strict';

/**
 * font-embed.js — DOCX font embedding (ECMA-376 Part 1, §15.2.13 "Font Part").
 *
 * WHY THIS EXISTS
 * ---------------
 * Pandoc has no `--embed-fonts` for docx and never writes `word/fonts/`. But its
 * docx writer copies certain parts of the `--reference-doc` archive through to the
 * output verbatim. Empirically (pandoc 3.8.3) the passthrough set includes:
 *
 *     word/fonts/*                    <- copied verbatim (whitelisted directory)
 *     word/media/*                    <- copied verbatim
 *     word/fontTable.xml              <- copied verbatim
 *     word/_rels/fontTable.xml.rels   <- copied verbatim
 *     word/settings.xml               <- content preserved (re-serialized)
 *
 * while arbitrary paths (e.g. `word/customJunk.bin`, `customdir/x.odttf`, or a
 * loose `word/loose.odttf`) are DROPPED. So font parts MUST live under
 * `word/fonts/` — that directory is load-bearing, not a convention.
 *
 * `[Content_Types].xml` is REGENERATED by pandoc from its own template, so any
 * Default you add to the reference doc is discarded. Fortunately pandoc's writer
 * emits the obfuscatedFont Default unconditionally, in every docx it produces:
 *
 *     <Default Extension="odttf"
 *              ContentType="application/vnd.openxmlformats-officedocument.obfuscatedFont"/>
 *
 * `contentTypeDefault` is still exported here so a caller can (a) assert that
 * declaration is present in the output and (b) stay correct if it ever has to
 * write a docx without pandoc in the loop.
 *
 * OBFUSCATION
 * -----------
 * Each font part is "obfuscated" (not encrypted — it is a trivially reversible
 * XOR whose only purpose is to stop a naive drag-out-and-install):
 *   - a GUID identifies the part; it goes in `w:fontKey` on the embed element
 *   - the GUID's 32 hex digits are read as 16 bytes, and that array is REVERSED
 *   - those 16 key bytes are XORed over the FIRST 32 bytes of the font, applied
 *     twice (key[i % 16] for i in 0..31)
 *   - every byte from offset 32 onward is left untouched
 *
 * The transform is its own inverse, so `obfuscateFont` doubles as the
 * de-obfuscator and is exported as `deobfuscateFont` for verification.
 *
 * LICENSING
 * ---------
 * Embedding is only lawful if the font permits it. `readFontMetadata` returns the
 * OS/2 `fsType` bits and `assertEmbeddable` enforces them. fsType is a bitfield
 * whose low 4 bits are mutually exclusive permission levels:
 *   0  Installable        — no restriction
 *   2  Restricted         — MUST NOT be embedded
 *   4  Preview & Print    — embed allowed, read-only documents only
 *   8  Editable           — embed allowed, document may be edited
 * plus bit 0x0100 (no subsetting) and 0x0200 (bitmap embedding only).
 *
 * @module font-embed
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

/** Relationship type URI for a font part. */
const FONT_REL_TYPE =
  'http://schemas.openxmlformats.org/officeDocument/2006/relationships/font';

/** Content type for an obfuscated font part. */
const OBFUSCATED_FONT_CONTENT_TYPE =
  'application/vnd.openxmlformats-officedocument.obfuscatedFont';

/** The `[Content_Types].xml` Default that makes `.odttf` parts legal. */
const CONTENT_TYPE_DEFAULT =
  `<Default Extension="odttf" ContentType="${OBFUSCATED_FONT_CONTENT_TYPE}"/>`;

/** Directory inside the package where font parts must live. */
const FONTS_DIR = 'word/fonts';

/** The four style slots Word understands, mapped to their fontTable elements. */
const STYLE_ELEMENTS = {
  regular: 'w:embedRegular',
  bold: 'w:embedBold',
  italic: 'w:embedItalic',
  boldItalic: 'w:embedBoldItalic',
};

const STYLE_ORDER = ['regular', 'bold', 'italic', 'boldItalic'];

// ---------------------------------------------------------------------------
// GUID / obfuscation
// ---------------------------------------------------------------------------

/**
 * Normalize a GUID to the 32 uppercase hex digits, stripping braces and hyphens.
 * @param {string} guid
 * @returns {string} 32 hex characters
 */
function normalizeGuid(guid) {
  const hex = String(guid).replace(/[{}\-\s]/g, '').toUpperCase();
  if (!/^[0-9A-F]{32}$/.test(hex)) {
    throw new Error(`font-embed: not a valid GUID: ${JSON.stringify(guid)}`);
  }
  return hex;
}

/**
 * Format 32 hex digits as a braced, hyphenated, uppercase GUID — the form Word
 * writes into `w:fontKey`.
 * @param {string} hex32
 * @returns {string} e.g. `{1F2E3D4C-5B6A-7988-9A0B-1C2D3E4F5061}`
 */
function formatGuid(hex32) {
  const h = normalizeGuid(hex32);
  return `{${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}}`;
}

/**
 * Derive the 16-byte obfuscation key from a GUID: read the hex digits as bytes
 * left-to-right, then reverse the byte array.
 * @param {string} guid
 * @returns {Buffer} 16 bytes
 */
function guidToKey(guid) {
  const hex = normalizeGuid(guid);
  return Buffer.from(hex, 'hex').reverse();
}

/**
 * Apply the ECMA-376 §15.2.13 obfuscation: XOR the reversed-GUID key over the
 * first 32 bytes of the font, key repeating every 16 bytes. Self-inverse.
 *
 * @param {Buffer} fontData raw font bytes (unmodified; a copy is returned)
 * @param {string} guid the GUID that will appear in `w:fontKey`
 * @returns {Buffer} obfuscated (or de-obfuscated) bytes
 */
function obfuscateFont(fontData, guid) {
  if (!Buffer.isBuffer(fontData)) {
    throw new TypeError('font-embed: fontData must be a Buffer');
  }
  if (fontData.length < 32) {
    throw new Error(
      `font-embed: font is only ${fontData.length} bytes; §15.2.13 requires at least 32`
    );
  }
  const key = guidToKey(guid);
  const out = Buffer.from(fontData); // copy — never mutate the caller's buffer
  for (let i = 0; i < 32; i++) {
    out[i] = out[i] ^ key[i % 16];
  }
  return out;
}

/** Alias: the obfuscation is an involution, so this is the same function. */
const deobfuscateFont = obfuscateFont;

/**
 * Produce a GUID for a font part. Deterministic by default so that rebuilding
 * the book from unchanged inputs yields a byte-identical reference doc; pass
 * `{random: true}` to mint a fresh one instead.
 *
 * @param {object} opts
 * @param {Buffer} [opts.fontData] font bytes, hashed into the GUID
 * @param {string} [opts.seed] extra seed material (e.g. `family/style`)
 * @param {boolean} [opts.random] mint a random GUID instead
 * @returns {string} braced uppercase GUID
 */
function makeFontGuid({ fontData, seed = '', random = false } = {}) {
  if (random || !fontData) {
    return formatGuid(crypto.randomBytes(16).toString('hex'));
  }
  const digest = crypto
    .createHash('sha256')
    .update(seed)
    .update(fontData)
    .digest();
  const bytes = Buffer.from(digest.subarray(0, 16));
  // Stamp RFC-4122 version 4 / variant 10x so the value is a well-formed GUID.
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  return formatGuid(bytes.toString('hex'));
}

// ---------------------------------------------------------------------------
// Font metadata (sfnt tables: OS/2, post, name)
// ---------------------------------------------------------------------------

/**
 * Parse the sfnt table directory.
 * @param {Buffer} data
 * @returns {Map<string, {offset: number, length: number}>}
 */
function readTableDirectory(data) {
  if (data.length < 12) throw new Error('font-embed: file too short to be a font');
  const tag = data.readUInt32BE(0);
  // 0x00010000 TrueType, 'OTTO' CFF, 'true'/'typ1' legacy Mac.
  const known = [0x00010000, 0x4f54544f, 0x74727565, 0x74797031];
  if (tag === 0x74746366) {
    throw new Error('font-embed: TrueType Collections (.ttc) are not supported');
  }
  if (!known.includes(tag)) {
    throw new Error(
      `font-embed: not an sfnt font (magic 0x${tag.toString(16).padStart(8, '0')})`
    );
  }
  const numTables = data.readUInt16BE(4);
  const tables = new Map();
  for (let i = 0; i < numTables; i++) {
    const rec = 12 + i * 16;
    if (rec + 16 > data.length) break;
    const name = data.toString('latin1', rec, rec + 4);
    tables.set(name, {
      offset: data.readUInt32BE(rec + 8),
      length: data.readUInt32BE(rec + 12),
    });
  }
  return tables;
}

/**
 * Read the typographic family name (name IDs 16 then 1) from the `name` table,
 * preferring the Windows/Unicode platform.
 * @param {Buffer} data
 * @param {Map} tables
 * @returns {string|null}
 */
function readFamilyName(data, tables) {
  const t = tables.get('name');
  if (!t || t.offset + 6 > data.length) return null;
  const base = t.offset;
  const count = data.readUInt16BE(base + 2);
  const stringOffset = data.readUInt16BE(base + 4);
  const candidates = [];
  for (let i = 0; i < count; i++) {
    const rec = base + 6 + i * 12;
    if (rec + 12 > data.length) break;
    const platformId = data.readUInt16BE(rec);
    const nameId = data.readUInt16BE(rec + 6);
    if (nameId !== 1 && nameId !== 16) continue;
    const len = data.readUInt16BE(rec + 8);
    const off = data.readUInt16BE(rec + 10);
    const start = base + stringOffset + off;
    if (start + len > data.length) continue;
    const raw = data.subarray(start, start + len);
    // Platform 3 (Windows) and platform 0 (Unicode) are UTF-16BE; 1 is MacRoman.
    const value =
      platformId === 1 ? raw.toString('latin1') : raw.toString('utf16le').length
        ? Buffer.from(raw).swap16().toString('utf16le')
        : raw.toString('latin1');
    candidates.push({ nameId, platformId, value: value.replace(/\0/g, '').trim() });
  }
  if (!candidates.length) return null;
  // Prefer typographic family (16) over legacy family (1); prefer Windows.
  candidates.sort(
    (a, b) => b.nameId - a.nameId || (b.platformId === 3 ? 1 : 0) - (a.platformId === 3 ? 1 : 0)
  );
  return candidates[0].value || null;
}

/**
 * Decide whether a font is monospaced by looking at actual glyph advance widths.
 *
 * The declarative flags cannot be trusted: both Atkinson families ship with
 * `post.isFixedPitch = 0`, an all-zero PANOSE and `sFamilyClass = 0`, so the
 * monospaced Mono family is indistinguishable from the proportional Next family
 * on metadata alone. Advance widths separate them cleanly — Mono's modal width
 * covers 99.7% of non-zero-width glyphs, Next's covers 3.2%.
 *
 * Zero-width glyphs (combining marks) are excluded, and a genuinely monospaced
 * font may still carry a few double-width glyphs, hence the ratio test rather
 * than requiring a single width.
 *
 * @param {Buffer} data
 * @param {Map} tables
 * @returns {boolean|null} null when hhea/hmtx are unreadable
 */
function detectMonospaceFromMetrics(data, tables) {
  const hhea = tables.get('hhea');
  const hmtx = tables.get('hmtx');
  if (!hhea || !hmtx) return null;
  if (hhea.offset + 36 > data.length) return null;
  const numHMetrics = data.readUInt16BE(hhea.offset + 34);
  if (!numHMetrics) return null;

  const counts = new Map();
  let nonZero = 0;
  for (let i = 0; i < numHMetrics; i++) {
    const off = hmtx.offset + i * 4;
    if (off + 2 > data.length) break;
    const w = data.readUInt16BE(off);
    if (w === 0) continue; // combining marks etc.
    nonZero++;
    counts.set(w, (counts.get(w) || 0) + 1);
  }
  if (nonZero === 0) return null;
  const modal = Math.max(...counts.values());
  return modal / nonZero >= 0.8;
}

/**
 * Extract the metadata needed to write a faithful `<w:font>` entry, plus the
 * licensing bits.
 *
 * @param {Buffer|string} fontOrPath font bytes or a path
 * @returns {{
 *   familyName: string|null, fsType: number, os2Version: number|null,
 *   panose: string, usb0: string, usb1: string, usb2: string, usb3: string,
 *   csb0: string, csb1: string, isFixedPitch: boolean,
 *   wordFamily: string, wordPitch: string
 * }}
 */
function readFontMetadata(fontOrPath) {
  const data = Buffer.isBuffer(fontOrPath)
    ? fontOrPath
    : fs.readFileSync(fontOrPath);
  const tables = readTableDirectory(data);

  const hex32 = (n) => (n >>> 0).toString(16).toUpperCase().padStart(8, '0');

  let fsType = 0;
  let os2Version = null;
  let panose = '00000000000000000000';
  let usb = [0, 0, 0, 0];
  let csb = [0, 0];

  const os2 = tables.get('OS/2');
  if (os2 && os2.offset + 78 <= data.length) {
    const o = os2.offset;
    os2Version = data.readUInt16BE(o);
    fsType = data.readUInt16BE(o + 8);
    panose = data.subarray(o + 32, o + 42).toString('hex').toUpperCase();
    usb = [
      data.readUInt32BE(o + 42),
      data.readUInt32BE(o + 46),
      data.readUInt32BE(o + 50),
      data.readUInt32BE(o + 54),
    ];
    // ulCodePageRange1/2 exist only from OS/2 version 1 onward.
    if (os2Version >= 1 && o + 86 <= data.length) {
      csb = [data.readUInt32BE(o + 78), data.readUInt32BE(o + 82)];
    }
  }

  const panoseBytes = Buffer.from(panose, 'hex');

  // Monospace detection, most-trusted signal first. Declarative flags are often
  // simply absent (see detectMonospaceFromMetrics), so metrics are the fallback
  // that actually decides it for the Atkinson families.
  let isFixedPitch = false;
  const post = tables.get('post');
  if (post && post.offset + 16 <= data.length) {
    isFixedPitch = data.readUInt32BE(post.offset + 12) !== 0;
  }
  // PANOSE proportion (byte 3) == 9 means monospaced for Latin Text (family 2).
  if (!isFixedPitch && panoseBytes[0] === 2 && panoseBytes[3] === 9) {
    isFixedPitch = true;
  }
  if (!isFixedPitch) {
    const byMetrics = detectMonospaceFromMetrics(data, tables);
    if (byMetrics === true) isFixedPitch = true;
  }

  // Map to Word's w:family vocabulary (ST_FontFamily: auto | decorative |
  // modern | roman | script | swiss). This is only a substitution hint — when
  // the face is embedded Word uses the real font — so "auto" is the honest
  // answer for a font that declares no classification at all, which is exactly
  // the case here (PANOSE and sFamilyClass are both zero).
  const familyClass =
    os2 && os2.offset + 32 <= data.length ? data.readInt16BE(os2.offset + 30) >> 8 : 0;
  let wordFamily = 'auto';
  if (isFixedPitch) {
    wordFamily = 'modern';
  } else if (panoseBytes[0] === 2) {
    const serifStyle = panoseBytes[1];
    if (serifStyle >= 2 && serifStyle <= 10) wordFamily = 'roman';
    else if (serifStyle >= 11 && serifStyle <= 15) wordFamily = 'swiss';
  } else if (panoseBytes[0] === 3) {
    wordFamily = 'script';
  }
  if (wordFamily === 'auto' && familyClass) {
    // IBM font-class IDs: 1..7 are the serif classes, 8 sans, 10 script.
    if (familyClass >= 1 && familyClass <= 7) wordFamily = 'roman';
    else if (familyClass === 8) wordFamily = 'swiss';
    else if (familyClass === 10) wordFamily = 'script';
    else if (familyClass === 12) wordFamily = 'decorative';
  }

  return {
    familyName: readFamilyName(data, tables),
    fsType,
    os2Version,
    panose,
    usb0: hex32(usb[0]),
    usb1: hex32(usb[1]),
    usb2: hex32(usb[2]),
    usb3: hex32(usb[3]),
    csb0: hex32(csb[0]),
    csb1: hex32(csb[1]),
    isFixedPitch,
    wordFamily,
    wordPitch: isFixedPitch ? 'fixed' : 'variable',
  };
}

/**
 * Describe fsType embedding permissions in human terms.
 * @param {number} fsType
 * @returns {{level: string, embeddable: boolean, editable: boolean,
 *            noSubsetting: boolean, bitmapOnly: boolean, summary: string}}
 */
function describeEmbeddingRights(fsType) {
  const perm = fsType & 0x000f;
  const noSubsetting = (fsType & 0x0100) !== 0;
  const bitmapOnly = (fsType & 0x0200) !== 0;
  let level;
  let embeddable = true;
  let editable = false;
  if (perm & 0x0002) {
    level = 'Restricted License (no embedding permitted)';
    embeddable = false;
  } else if (perm & 0x0004) {
    level = 'Preview & Print embedding (read-only documents)';
  } else if (perm & 0x0008) {
    level = 'Editable embedding';
    editable = true;
  } else {
    level = 'Installable embedding (no restrictions)';
    editable = true;
  }
  return {
    level,
    embeddable,
    editable,
    noSubsetting,
    bitmapOnly,
    summary:
      `fsType=${fsType} (0x${fsType.toString(16).padStart(4, '0')}): ${level}` +
      (noSubsetting ? '; no subsetting' : '') +
      (bitmapOnly ? '; bitmap embedding only' : ''),
  };
}

/**
 * Throw unless the font permits embedding in an editable document.
 * @param {string} label identifier used in the error message
 * @param {number} fsType
 * @param {boolean} [requireEditable=true] docx files the user will edit need
 *        Editable or Installable rights; Preview&Print is not enough.
 */
function assertEmbeddable(label, fsType, requireEditable = true) {
  const rights = describeEmbeddingRights(fsType);
  if (!rights.embeddable) {
    throw new Error(
      `font-embed: ${label} forbids embedding — ${rights.summary}`
    );
  }
  if (requireEditable && !rights.editable) {
    throw new Error(
      `font-embed: ${label} allows only preview/print embedding, but the output ` +
        `is an editable document — ${rights.summary}`
    );
  }
  return rights;
}

// ---------------------------------------------------------------------------
// XML helpers
// ---------------------------------------------------------------------------

function xmlEscapeAttr(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Build every piece needed to embed a set of faces in a docx package.
 *
 * @param {object} options
 * @param {Array<{family: string, style: string, ttfPath?: string, data?: Buffer}>}
 *        options.faces faces to embed. `style` is one of
 *        regular | bold | italic | boldItalic.
 * @param {number} [options.startRelIdNumber=1000] first numeric suffix for the
 *        generated `rIdN` values. The fontTable rels part has its own id space
 *        (it is not document.xml.rels), but a high base keeps ids obviously
 *        distinct from pandoc's when reading the XML.
 * @param {boolean} [options.randomGuids=false] mint random GUIDs instead of
 *        deriving them from content (deterministic builds are the default).
 * @param {boolean} [options.requireEditable=true] enforce Editable/Installable
 *        fsType rights.
 * @param {number} [options.fontIndexBase=1] first N in `fontN.odttf`.
 *
 * @returns {{
 *   parts: Array<{path: string, data: Buffer, guid: string, relId: string,
 *                 family: string, style: string, sourceBytes: number}>,
 *   fonts: Array<object>,
 *   fontTableEntries: string,
 *   relationships: Array<{id: string, type: string, target: string}>,
 *   fontTableRelsXml: string,
 *   contentTypeDefault: string,
 *   settingsFlags: string,
 *   totalEmbeddedBytes: number,
 *   licensing: Array<object>
 * }}
 */
function buildFontEmbedding(options = {}) {
  const {
    faces,
    startRelIdNumber = 1000,
    randomGuids = false,
    requireEditable = true,
    fontIndexBase = 1,
  } = options;

  if (!Array.isArray(faces) || faces.length === 0) {
    throw new Error('font-embed: `faces` must be a non-empty array');
  }

  // Group faces by family, preserving first-seen family order.
  const families = new Map();
  const parts = [];
  const relationships = [];
  const licensing = [];
  let relCounter = startRelIdNumber;
  let fontIndex = fontIndexBase;
  let totalEmbeddedBytes = 0;

  for (const face of faces) {
    const { family, style } = face;
    if (!family) throw new Error('font-embed: each face needs a `family`');
    if (!STYLE_ELEMENTS[style]) {
      throw new Error(
        `font-embed: unknown style ${JSON.stringify(style)} for ${family}; ` +
          `expected one of ${STYLE_ORDER.join(', ')}`
      );
    }
    const source = face.ttfPath ? path.resolve(face.ttfPath) : null;
    const data = face.data
      ? Buffer.from(face.data)
      : fs.readFileSync(source);

    const label = `${family} ${style}${source ? ` (${path.basename(source)})` : ''}`;
    const meta = readFontMetadata(data);
    const rights = assertEmbeddable(label, meta.fsType, requireEditable);
    licensing.push({
      family,
      style,
      path: source,
      fsType: meta.fsType,
      ...rights,
    });

    if (!families.has(family)) {
      families.set(family, { family, meta, styles: new Map() });
    }
    const entry = families.get(family);
    if (entry.styles.has(style)) {
      throw new Error(
        `font-embed: duplicate style "${style}" for family "${family}"`
      );
    }
    // The regular face carries the most representative metrics for <w:font>.
    if (style === 'regular') entry.meta = meta;

    const guid = makeFontGuid({
      fontData: data,
      seed: `${family}|${style}`,
      random: randomGuids,
    });
    const relId = `rId${relCounter++}`;
    const partName = `font${fontIndex++}.odttf`;
    const obfuscated = obfuscateFont(data, guid);

    const part = {
      path: `${FONTS_DIR}/${partName}`,
      data: obfuscated,
      guid,
      relId,
      family,
      style,
      sourcePath: source,
      sourceBytes: data.length,
    };
    parts.push(part);
    totalEmbeddedBytes += obfuscated.length;
    relationships.push({
      id: relId,
      type: FONT_REL_TYPE,
      target: `fonts/${partName}`, // relative to word/, the rels part's base
    });
    entry.styles.set(style, part);
  }

  // ---- word/fontTable.xml entries -----------------------------------------
  const fontElements = [];
  const fonts = [];
  for (const { family, meta, styles } of families.values()) {
    const embeds = STYLE_ORDER.filter((s) => styles.has(s)).map((s) => {
      const p = styles.get(s);
      return `    <${STYLE_ELEMENTS[s]} r:id="${p.relId}" w:fontKey="${p.guid}"/>`;
    });
    const xml =
      `  <w:font w:name="${xmlEscapeAttr(family)}">\n` +
      `    <w:panose1 w:val="${meta.panose}"/>\n` +
      `    <w:charset w:val="00"/>\n` +
      `    <w:family w:val="${meta.wordFamily}"/>\n` +
      `    <w:pitch w:val="${meta.wordPitch}"/>\n` +
      `    <w:sig w:usb0="${meta.usb0}" w:usb1="${meta.usb1}" w:usb2="${meta.usb2}"` +
      ` w:usb3="${meta.usb3}" w:csb0="${meta.csb0}" w:csb1="${meta.csb1}"/>\n` +
      embeds.join('\n') +
      `\n  </w:font>`;
    fontElements.push(xml);
    fonts.push({
      family,
      xml,
      styles: [...styles.keys()],
      metadata: meta,
    });
  }

  // ---- word/_rels/fontTable.xml.rels --------------------------------------
  const fontTableRelsXml =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n` +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n` +
    relationships
      .map(
        (r) =>
          `  <Relationship Id="${r.id}" Type="${r.type}" Target="${xmlEscapeAttr(r.target)}"/>`
      )
      .join('\n') +
    `\n</Relationships>\n`;

  return {
    parts,
    fonts,
    fontTableEntries: fontElements.join('\n'),
    relationships,
    fontTableRelsXml,
    contentTypeDefault: CONTENT_TYPE_DEFAULT,
    // Word only honours embedded fonts when the document asks it to; without
    // embedTrueTypeFonts a re-save will drop word/fonts/ entirely.
    settingsFlags: '<w:embedTrueTypeFonts/><w:saveSubsetFonts w:val="false"/>',
    totalEmbeddedBytes,
    licensing,
  };
}

/**
 * Splice generated `<w:font>` elements into an existing `word/fontTable.xml`,
 * replacing any pre-existing entry for the same font name so repeated runs are
 * idempotent.
 *
 * @param {string} fontTableXml current contents of word/fontTable.xml
 * @param {string} fontEntries `fontTableEntries` from {@link buildFontEmbedding}
 * @param {string[]} [families] font names whose existing entries to drop
 * @returns {string} updated XML
 */
function injectFontTableEntries(fontTableXml, fontEntries, families = []) {
  let xml = fontTableXml;
  for (const family of families) {
    // Remove an existing <w:font w:name="Family"> ... </w:font> block.
    const re = new RegExp(
      `\\s*<w:font\\b[^>]*w:name="${family.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"[\\s\\S]*?</w:font>`,
      'g'
    );
    xml = xml.replace(re, '');
    // Also handle the self-closing degenerate form.
    const reSelf = new RegExp(
      `\\s*<w:font\\b[^>]*w:name="${family.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"[^>]*/>`,
      'g'
    );
    xml = xml.replace(reSelf, '');
  }
  const close = xml.lastIndexOf('</w:fonts>');
  if (close === -1) {
    throw new Error('font-embed: fontTable.xml has no </w:fonts> element');
  }
  return xml.slice(0, close) + fontEntries + '\n' + xml.slice(close);
}

/**
 * Ensure `word/settings.xml` carries the flags Word needs to keep the embedded
 * fonts on re-save. Idempotent.
 *
 * @param {string} settingsXml
 * @returns {string}
 */
function injectSettingsFlags(settingsXml) {
  let xml = settingsXml;
  const additions = [];
  if (!/<w:embedTrueTypeFonts\b/.test(xml)) additions.push('<w:embedTrueTypeFonts/>');
  if (!/<w:saveSubsetFonts\b/.test(xml)) {
    additions.push('<w:saveSubsetFonts w:val="false"/>');
  }
  if (!additions.length) return xml;

  // w:embedTrueTypeFonts / w:saveSubsetFonts sit early in CT_Settings; placing
  // them right after <w:settings ...> keeps schema order valid in practice, but
  // anchoring to an existing sibling is safer when one is present.
  if (/<w:embedSystemFonts\b[^>]*\/>/.test(xml)) {
    return xml.replace(
      /(<w:embedSystemFonts\b[^>]*\/>)/,
      `$1${additions.join('')}`
    );
  }
  return xml.replace(/(<w:settings\b[^>]*>)/, `$1${additions.join('')}`);
}

/**
 * Ensure `[Content_Types].xml` declares the odttf Default. Pandoc emits this on
 * its own, so this is for callers writing a package without pandoc.
 * @param {string} contentTypesXml
 * @returns {string}
 */
function injectContentTypeDefault(contentTypesXml) {
  if (/Extension="odttf"/i.test(contentTypesXml)) return contentTypesXml;
  return contentTypesXml.replace(/(<Types\b[^>]*>)/, `$1${CONTENT_TYPE_DEFAULT}`);
}

module.exports = {
  buildFontEmbedding,
  obfuscateFont,
  deobfuscateFont,
  makeFontGuid,
  guidToKey,
  normalizeGuid,
  formatGuid,
  readFontMetadata,
  readTableDirectory,
  describeEmbeddingRights,
  assertEmbeddable,
  injectFontTableEntries,
  injectSettingsFlags,
  injectContentTypeDefault,
  FONT_REL_TYPE,
  OBFUSCATED_FONT_CONTENT_TYPE,
  CONTENT_TYPE_DEFAULT,
  FONTS_DIR,
  STYLE_ORDER,
};
